CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  varchar(255)                            NOT NULL,
    email varchar(255)                            NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar(50)                             NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    lat NUMERIC                                 NOT NULL,
    lon NUMERIC                                 NOT NULL,
    CONSTRAINT location_lat_lon UNIQUE (lat, lon)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pinned boolean DEFAULT FALSE                   NOT NULL,
    title  varchar(50)                             NOT NULL

);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY               NOT NULL PRIMARY KEY,
    annotation         varchar(2000)                                         NOT NULL,
    category_id        bigint REFERENCES categories (id),
    created_on         timestamp without time zone default current_timestamp NOT NULL,
    description        varchar(7000),
    event_date         timestamp without time zone                           NOT NULL,
    user_id            bigint                                                NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    location_id        bigint REFERENCES locations (id),
    paid               boolean                     DEFAULT false             NOT NULL,
    participant_limit  integer                     DEFAULT 0                 NOT NULL,
    published_on       timestamp without time ZONE,
    request_moderation boolean                     DEFAULT TRUE              NOT NULL,
    state              varchar(50)                 DEFAULT 'PENDING'         NOT NULL,
    title              varchar(120)                                          NOT NULL,
    constraint event_participant_limit_positive_chk check (participant_limit >= 0),
    constraint event_date_after_create_chk check (event_date + interval '2' hour >= created_on)
);

create table if not exists requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY       NOT NULL PRIMARY KEY,
    event_id     bigint REFERENCES events (id) ON DELETE CASCADE,
    requester_id bigint REFERENCES users (id) ON DELETE CASCADE,
    status       varchar(50)                 DEFAULT 'PENDING' NOT NULL,
    created      timestamp without time zone default current_timestamp,
    constraint request_event_req_u_idx unique (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id bigint REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       bigint REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT compilation_event_pk PRIMARY KEY (compilation_id, event_id)
);